/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms. 
 */

#include <iostream>

using namespace std;

#define limit 4000000

int main() {
    system("@cls||clear");
    int sum = 0 ;
    int x1 = 1;
    int x2 = 2;

    while ( x1 < limit ) {
        if ( (x1 & 1) == 0 ) { // x % 2 == 0
            sum += x1;
        }
        x2=x1+x2; // x2 = sum
        x1=x2-x1; // x1 = the old value of x2
    }

    cout << sum;

    return 0;
}